### ISSUE TITLE
Is this because the effect is not set?

### ISSUE THREAD

**Issue by madtomic** [games647/McCombatLevel#13]
[23:04:55 INFO]: [McCombatLevel] Enabling McCombatLevel v1.7.4
[23:04:55 ERROR]: Error occurred while enabling McCombatLevel v1.7.4 (Is it up t
o date?)
java.lang.NullPointerException
        at com.gmail.mrphpfan.mccombatlevel.Effects.create(Effects.java:13) ~[?:
?]
        at com.gmail.mrphpfan.mccombatlevel.McCombatLevel.loadConfiguration(McCo
mbatLevel.java:198) ~[?:?]
        at com.gmail.mrphpfan.mccombatlevel.McCombatLevel.onEnable(McCombatLevel
.java:59) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[p
aperspigot-1.7.10.jar:git-PaperSpigot-52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:332) [paperspigot-1.7.10.jar:git-PaperSpigot-52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:412) [paperspigot-1.7.10.jar:git-PaperSpigot-52]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.jav
a:477) [paperspigot-1.7.10.jar:git-PaperSpigot-52]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.
java:395) [paperspigot-1.7.10.jar:git-PaperSpigot-52]
        at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:3
54) [paperspigot-1.7.10.jar:git-PaperSpigot-52]
        at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:3
28) [paperspigot-1.7.10.jar:git-PaperSpigot-52]
        at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:2
84) [paperspigot-1.7.10.jar:git-PaperSpigot-52]
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.jav
a:227) [paperspigot-1.7.10.jar:git-PaperSpigot-52]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java
:493) [paperspigot-1.7.10.jar:git-PaperSpigot-52]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:6
28) [paperspigot-1.7.10.jar:git-PaperSpigot-52]

**Comment by madtomic** [comment]
This is on a fresh install and first load. This also appears on reload or restart.

**Comment by games647** [comment]
I know. I fixed it now. I upload the commit later.

**Comment by madtomic** [comment]
I also try to add in type and load again and it still load with errors. I hope the commit fixes this.

**Comment by madtomic** [comment]
This fix is related to the maven fail build?

**Comment by games647** [comment]
yes

**Comment by madtomic** [comment]
Do I need to reopen this issue or you will just commit a file and fix this?
